### ISSUE TITLE
build takes 12-13 seconds

### ISSUE THREAD

**Issue by staabm** [ergebnis/composer-root-version-action#54]
hey andreas!

when running a github action which contains `ergebnis/composer-root-version-action@main` it requires an additional 12-13 seconds to build this action:

![grafik](https://user-images.githubusercontent.com/120441/169298148-62efa130-cf6d-4215-b733-289f532221e2.png)
as you can see a step using 12-13 seconds in a job which takes 39 seconds overall seems a bit too much.

it feels like this adds a rather big overhead, so I just want to ask whether this is expected? wdyt?

**Comment by localheinz** [comment]
@staabm 

Probably related to my changes!

**Comment by localheinz** [comment]
@staabm 

Can you try using `ergebnis/composer-root-version-action@0.2.1` for now?

**Comment by staabm** [comment]
sure thing, thank you

**Comment by localheinz** [comment]
@staabm 

As an alternative to using this action, and following https://github.com/ergebnis/.github/pull/87, can you try using the composite action added there?

See #58 as an example!


```diff
        - name: "Determine composer root version action"
-         uses: "ergebnis/composer-root-version-action@main"
+         uses: "ergebnis/.github/actions/composer/determine-root-version@1.5.0"
          with:
            branch: "branch-alias"
-           path: "path-to-directory-containing-composer.json"
+           working-directory: "path-to-directory-containing-composer.json"

**Comment by localheinz** [comment]
@staabm 

With a composite action, the setup takes about 1 second!

**Comment by staabm** [comment]
will give it a try later today, or maybe tomorrow morgen.

thank you so far

**Comment by staabm** [comment]
I tried using a relative path, which didn't work
```
        uses: "ergebnis/.github/actions/composer/determine-root-version@1.5.0"
        with:
          branch: "${{ github.event.repository.default_branch }}"
          working-directory: "../../composer.json" 
```

=> The value for the "working-directory" input needs to be an existing directory. The directory "../../composer.json" does not exist.

----

after that I tried a absolute path
```
        uses: "ergebnis/.github/actions/composer/determine-root-version@1.5.0"
        with:
          branch: "${{ github.event.repository.default_branch }}"
          working-directory: "/composer.json"
```

which didn't work

----

after that I tried

```
        uses: "ergebnis/.github/actions/composer/determine-root-version@1.5.0"
        with:
          branch: "${{ github.event.repository.default_branch }}"
          working-directory: "../../"
```

which worked only for some jobs..

----

couldn't the working-directory default to the repo-root when not provided?
=> I tried that, and it seems it what I need.


I guess lesson learned is: 
- most repos will not need the working-directory param, and should just omit it.
- in case the working directory is given, it might make sense to somehow document from which path this parameter is relative to and if a path is given which includes a filename, a meaningfull error would be great.
- it works great for me, when I just omit `working-directory`
